// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.1
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xpid_regulator.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XPid_regulator_CfgInitialize(XPid_regulator *InstancePtr, XPid_regulator_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Axilites_BaseAddress = ConfigPtr->Axilites_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XPid_regulator_Start(XPid_regulator *InstancePtr) {
    u32 Data;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XPid_regulator_ReadReg(InstancePtr->Axilites_BaseAddress, XPID_REGULATOR_AXILITES_ADDR_AP_CTRL) & 0x80;
    XPid_regulator_WriteReg(InstancePtr->Axilites_BaseAddress, XPID_REGULATOR_AXILITES_ADDR_AP_CTRL, Data | 0x01);
}

u32 XPid_regulator_IsDone(XPid_regulator *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XPid_regulator_ReadReg(InstancePtr->Axilites_BaseAddress, XPID_REGULATOR_AXILITES_ADDR_AP_CTRL);
    return (Data >> 1) & 0x1;
}

u32 XPid_regulator_IsIdle(XPid_regulator *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XPid_regulator_ReadReg(InstancePtr->Axilites_BaseAddress, XPID_REGULATOR_AXILITES_ADDR_AP_CTRL);
    return (Data >> 2) & 0x1;
}

u32 XPid_regulator_IsReady(XPid_regulator *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XPid_regulator_ReadReg(InstancePtr->Axilites_BaseAddress, XPID_REGULATOR_AXILITES_ADDR_AP_CTRL);
    // check ap_start to see if the pcore is ready for next input
    return !(Data & 0x1);
}

void XPid_regulator_EnableAutoRestart(XPid_regulator *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XPid_regulator_WriteReg(InstancePtr->Axilites_BaseAddress, XPID_REGULATOR_AXILITES_ADDR_AP_CTRL, 0x80);
}

void XPid_regulator_DisableAutoRestart(XPid_regulator *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XPid_regulator_WriteReg(InstancePtr->Axilites_BaseAddress, XPID_REGULATOR_AXILITES_ADDR_AP_CTRL, 0);
}

u32 XPid_regulator_Get_return(XPid_regulator *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XPid_regulator_ReadReg(InstancePtr->Axilites_BaseAddress, XPID_REGULATOR_AXILITES_ADDR_AP_RETURN);
    return Data;
}
void XPid_regulator_Set_Ref(XPid_regulator *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XPid_regulator_WriteReg(InstancePtr->Axilites_BaseAddress, XPID_REGULATOR_AXILITES_ADDR_REF_DATA, Data);
}

u32 XPid_regulator_Get_Ref(XPid_regulator *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XPid_regulator_ReadReg(InstancePtr->Axilites_BaseAddress, XPID_REGULATOR_AXILITES_ADDR_REF_DATA);
    return Data;
}

void XPid_regulator_Set_Fdb(XPid_regulator *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XPid_regulator_WriteReg(InstancePtr->Axilites_BaseAddress, XPID_REGULATOR_AXILITES_ADDR_FDB_DATA, Data);
}

u32 XPid_regulator_Get_Fdb(XPid_regulator *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XPid_regulator_ReadReg(InstancePtr->Axilites_BaseAddress, XPID_REGULATOR_AXILITES_ADDR_FDB_DATA);
    return Data;
}

void XPid_regulator_InterruptGlobalEnable(XPid_regulator *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XPid_regulator_WriteReg(InstancePtr->Axilites_BaseAddress, XPID_REGULATOR_AXILITES_ADDR_GIE, 1);
}

void XPid_regulator_InterruptGlobalDisable(XPid_regulator *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XPid_regulator_WriteReg(InstancePtr->Axilites_BaseAddress, XPID_REGULATOR_AXILITES_ADDR_GIE, 0);
}

void XPid_regulator_InterruptEnable(XPid_regulator *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XPid_regulator_ReadReg(InstancePtr->Axilites_BaseAddress, XPID_REGULATOR_AXILITES_ADDR_IER);
    XPid_regulator_WriteReg(InstancePtr->Axilites_BaseAddress, XPID_REGULATOR_AXILITES_ADDR_IER, Register | Mask);
}

void XPid_regulator_InterruptDisable(XPid_regulator *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XPid_regulator_ReadReg(InstancePtr->Axilites_BaseAddress, XPID_REGULATOR_AXILITES_ADDR_IER);
    XPid_regulator_WriteReg(InstancePtr->Axilites_BaseAddress, XPID_REGULATOR_AXILITES_ADDR_IER, Register & (~Mask));
}

void XPid_regulator_InterruptClear(XPid_regulator *InstancePtr, u32 Mask) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XPid_regulator_WriteReg(InstancePtr->Axilites_BaseAddress, XPID_REGULATOR_AXILITES_ADDR_ISR, Mask);
}

u32 XPid_regulator_InterruptGetEnabled(XPid_regulator *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XPid_regulator_ReadReg(InstancePtr->Axilites_BaseAddress, XPID_REGULATOR_AXILITES_ADDR_IER);
}

u32 XPid_regulator_InterruptGetStatus(XPid_regulator *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XPid_regulator_ReadReg(InstancePtr->Axilites_BaseAddress, XPID_REGULATOR_AXILITES_ADDR_ISR);
}

