// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.1
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xpid_regulator.h"

extern XPid_regulator_Config XPid_regulator_ConfigTable[];

XPid_regulator_Config *XPid_regulator_LookupConfig(u16 DeviceId) {
	XPid_regulator_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XPID_REGULATOR_NUM_INSTANCES; Index++) {
		if (XPid_regulator_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XPid_regulator_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XPid_regulator_Initialize(XPid_regulator *InstancePtr, u16 DeviceId) {
	XPid_regulator_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XPid_regulator_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XPid_regulator_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

